services:
  piston:
    image: ghcr.io/engineer-man/piston
    container_name: piston
    restart: unless-stopped
    privileged: true
    ports:
      - "2000:2000"
    volumes:
      - ./piston-data/packages:/piston/packages
    tmpfs:
      - /piston/jobs:exec,uid=1000,gid=1000,mode=711