# Generated by Django 5.0.14 on 2026-04-28 00:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.TextField()),
                ('answer', models.TextField(help_text='Réponse en markdown')),
                ('category', models.CharField(blank=True, max_length=100)),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('hit_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faq_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrée FAQ',
                'verbose_name_plural': 'Entrées FAQ',
                'ordering': ['-updated_at'],
            },
        ),
    ]
